use crate::content::{SectionDescription, SectionHeader};

pub struct Project {
    pub title: &'static str,
    pub description: &'static str,
    pub tags: &'static [&'static str],
    pub gradient: &'static str,
    pub version: &'static str,
    pub stars: u32,
    pub forks: u32,
    pub featured: bool,
    pub repo_url: Option<&'static str>,
}

pub const PROJECT_SECTION: SectionHeader = SectionHeader {
    number: "03 — projects",
    title: "Selected work",
    description: Some(SectionDescription::Link {
        label: "view all on github",
        href: "https://click.scitechai.ru/gitearad",
    }),
    centered: false,
};

pub const PROJECTS: &[Project] = &[
    Project {
        title: "yew-folio",
        description: "Personal portfolio built with Rust and Yew framework, compiled to WebAssembly for high-performance client-side rendering. Features component-based architecture with Tailwind CSS. Serves as a practical exploration of Rust's ownership model and systems programming in web development.",
        tags: &["rust", "yew"],
        gradient: "from-rust-500 via-rust-600 to-rust-800",
        version: "v0.1.0",
        stars: 1,
        forks: 0,
        featured: true,
        repo_url: Some("https://click.scitechai.ru/yewfolio"),
    },
    Project {
        title: "q-mech",
        description: "Adapted SymPy documentation for structural engineering. Step-by-step examples for calculating beams and trusses, featuring Macaulay's method, interactive notebooks, and FEM verification workflows.",
        tags: &["Python", "simpy", "beam", "truss", "Macaulay"],
        gradient: "from-blue-600 via-indigo-700 to-purple-800",
        version: "v1.0.0",
        stars: 2,
        forks: 0,
        featured: false,
        repo_url: Some("https://click.scitechai.ru/qmech"),
    },
    Project {
        title: "psow",
        description: "Technical research experiment evaluating the ergonomics, migration cost, and safety guarantees of two modern stacks — C++20 with Eigen and Rust — for porting a legacy C++/MFC finite element kernel. The scope is deliberately narrow: a single 15-node quadratic triangular prism (PSOW) element, with shape function formulas transcribed verbatim from the original reference implementation (math preserved bit-for-bit). The experiment is not production code; the repository serves as a working scratchpad for engineering notes and comparative observations prior to a full FEM kernel migration decision. Both ports are covered by an identical verification suite: partition of unity checks, Kronecker delta property at nodes, Jacobian non-singularity across the reference element, and derivative cross-validation against finite-difference approximations. The original computational code was authored by a third party and is used here as a reference with the author's consent; licensing of this repository and any further publication remain subject to separate agreement with the original author.",
        tags: &[
            "c++20",
            "rust",
            "eigen",
            "fem",
            "finite element method",
            "shape functions",
            "jacobian",
            "partition of unity",
            "kronecker delta",
            "finite differences",
            "numerical methods",
            "scientific computing",
            "serendipity elements",
        ],
        gradient: "from-emerald-700 via-teal-800 to-slate-900",
        version: "v1.0.0",
        stars: 0,
        forks: 0,
        featured: false,
        repo_url: Some("https://click.scitechai.ru/psow"),
    },
    Project {
        title: "t1dwh",
        description: "Academic prototype (2024 – early 2025) exploring distributed Data Warehouse (DWH) architectural patterns on Greenplum (MPP, PostgreSQL-based) with Apache Airflow for deterministic ETL orchestration. The project formalizes evaluation of DWH topologies (Kimball 1-2NF vs Inmon 3NF vs Data Vault) and executes a Kimball-derived dimensional model optimized for OLAP query patterns. Core engineering deliverables include a multi-tiered data architecture (Staging, DDS, Data Marts), implementation of Slowly Changing Dimensions (SCD Type 2) via hash-based change detection (MD5) for temporal data consistency, and storage engine optimization via columnar orientation, ZSTD/RLE compression algorithms, and range partitioning. The ETL subsystem utilizes postgres_fdw for federated data ingestion, Airflow DAGs with XCom for stateful inter-task coordination, and PL/pgSQL functions for incremental loading with high-water mark semantics. The prototype enforces idempotency, rigorous exception handling with quarantine patterns, and transaction isolation analysis (Repeatable Read, Serializable) for data consistency guarantees.",
        tags: &[
            "greenplum",
            "postgresql",
            "apache airflow",
            "dimensional modeling",
            "kimball",
            "scd type 2",
            "columnar storage",
            "zstd",
            "rle",
            "range partitioning",
            "etl",
            "data marts"
        ],
        gradient: "bg-gradient-to-r from-fuchsia-600 to-purple-600",
        version: "v1.0.0",
        stars: 0,
        forks: 0,
        featured: false,
        repo_url: Some("https://click.scitechai.ru/t1dwh"),
    },
    Project {
        title: "SteelFrame Hub",
        description: "A high-load enterprise web platform for a steel frame manufacturing company, combining an online store with complex engineering tools. The system features a robust corporate website, a seamless user account dashboard, and custom dynamic price calculators. It hosts an SEO-optimized blog with 200+ technical articles and integrates a comprehensive testing system with diverse quizzes on structural design and programming. Built with a full-scale feedback loop, including user comments, ratings, and likes across all modules.",
        tags: &["django", "python", "postgresql", "e-commerce", "blog"],
        gradient: "from-slate-700 via-cyan-800 to-emerald-950",
        version: "v1.1.0",
        stars: 0,
        forks: 0,
        featured: false,
        repo_url: Some("https://click.scitechai.ru/scitech"),
    },
];
